// index.js
import Head from "next/head";
import Layout from "../components/Layout";
import BootstrapCarousel from "../components/Carousel";
import Card from "../components/Card";
import { renderProductCategory } from "../utils/ProductUtils";
import Link from "next/link";
import Footer from "../components/Footer";
import styles from "../styles/Index.module.css";



export default function Home() {
  return (
    <div>
      <div>
        <Head>
          <title>Next.js Carousels</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout title={"home page"} />
        <main>
          <BootstrapCarousel />
        </main>
      </div>

      <div>
        <section id="shop">
          <h2 className={`text-center mt-5 mb-5 ${styles.indexTitle}`}>SHOP</h2>
        </section>
        <Card />
      </div>
      <div className="container2">
        <h2 className={`text-center mt-5 mb-5 ${styles.indexTitle}`}>
          LIST OF PRODUCTS
        </h2>
        <div className="container">
          <h2
            className={`text-center mt-5 mb-5 ${styles.indexTitle}`}
            id="men-section"
          >
            MEN
          </h2>
          {renderProductCategory("Men", "Top")}
          {renderProductCategory("Men", "Bottom")}
          {renderProductCategory("Men", "Shoes")}
          <h2
            className={`text-center mt-5 mb-5 ${styles.indexTitle}`}
            id="women-section"
          >
            WOMEN
          </h2>
          {renderProductCategory("Women", "Top")}
          {renderProductCategory("Women", "Bottom")}
          {renderProductCategory("Women", "Shoes")}
        </div>
      </div>
      <div id="footer">
        <Footer />
      </div>
    </div>
  );
}
